const mockEvents = [
  {
    id: "evt-001",
    type: "Fire",
    confidence: 92,
    lat: 34.0522,
    lng: -118.2437,
    title: "Wind-driven wildfire near Los Angeles foothills",
    source: "CalFire alert network",
    timestamp: "2026-01-30T18:45:00Z",
    details: "Rapid spread reported in dry brush with smoke plumes visible from downtown.",
  },
  {
    id: "evt-002",
    type: "Flood",
    confidence: 86,
    lat: 29.7604,
    lng: -95.3698,
    title: "Flash flooding across Houston metro corridors",
    source: "NOAA incident feed",
    timestamp: "2026-01-30T22:20:00Z",
    details: "Multiple underpasses flooded after 6 inches of rain in two hours.",
  },
  {
    id: "evt-003",
    type: "Fire",
    confidence: 78,
    lat: 37.7749,
    lng: -122.4194,
    title: "Industrial fire reported in Bay Area warehouse zone",
    source: "Local emergency radio",
    timestamp: "2026-01-29T09:10:00Z",
    details: "Hazmat teams dispatched; residents advised to shelter in place.",
  },
  {
    id: "evt-004",
    type: "Flood",
    confidence: 69,
    lat: 40.7128,
    lng: -74.006,
    title: "Coastal surge warnings for lower Manhattan",
    source: "City infrastructure bulletin",
    timestamp: "2026-01-28T14:05:00Z",
    details: "High tide expected to exceed protective barriers by 0.4 meters.",
  },
];

export default mockEvents;
